name: Automate Issues

on:
  issues:
    types: [opened]

jobs:

  automated-issue:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v5

      # SetUp python
      - name: SetUp Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Install requirements
      - name: Install Requirements
        run: pip install requests

      # Runs a single command using the runners shell
      - name: Automate Issue
        env:
          API_KEY: ${{ secrets.GH_API_TOKEN }}
          REPO: ${{ github.repository }}
        run: python .github/workflows/issues.py
